# Generated by Django 5.2.4 on 2025-08-31 18:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('date_of_birth', models.DateField(verbose_name='Date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{8,15}$')], verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(max_length=20, unique=True, verbose_name="Clé d'accès")),
                ('password', models.CharField(max_length=12, verbose_name='Mot de passe')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valide à partir de')),
                ('valid_until', models.DateTimeField(verbose_name="Valide jusqu'à")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'accès")),
                ('last_accessed', models.DateTimeField(blank=True, null=True, verbose_name='Dernier accès')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_via_sms', models.BooleanField(default=False, verbose_name='Envoyé par SMS')),
                ('sent_via_email', models.BooleanField(default=False, verbose_name='Envoyé par Email')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Accès Patient',
                'verbose_name_plural': 'Accès Patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
