# Generated by Django 5.2.4 on 2025-09-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientaccess',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='patientaccess',
            name='valid_until',
        ),
        migrations.AlterField(
            model_name='patientaccess',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='access', to='patients.patient'),
        ),
    ]
