# Generated by Django 5.2.4 on 2025-09-02 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patientaccess_valid_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['first_name', 'last_name'], name='patients_pa_first_n_a142c0_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_number'], name='patients_pa_phone_n_933975_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['email'], name='patients_pa_email_bb026d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_at'], name='patients_pa_created_542792_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['date_of_birth'], name='patients_pa_date_of_4302f5_idx'),
        ),
        migrations.AddIndex(
            model_name='patientaccess',
            index=models.Index(fields=['access_key'], name='patients_pa_access__ce1dc1_idx'),
        ),
        migrations.AddIndex(
            model_name='patientaccess',
            index=models.Index(fields=['is_active'], name='patients_pa_is_acti_1c7174_idx'),
        ),
        migrations.AddIndex(
            model_name='patientaccess',
            index=models.Index(fields=['access_count'], name='patients_pa_access__67a5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='patientaccess',
            index=models.Index(fields=['last_accessed'], name='patients_pa_last_ac_bc8535_idx'),
        ),
        migrations.AddIndex(
            model_name='patientaccess',
            index=models.Index(fields=['created_at'], name='patients_pa_created_1f7472_idx'),
        ),
    ]
