# Generated by Django 5.2.4 on 2026-03-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_phone_unique_email_optional'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_pa_date_of_4302f5_idx',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['age'], name='patients_pa_age_353768_idx'),
        ),
    ]
