# Generated by Django 5.2.4 on 2026-03-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_patient_patients_pa_date_of_4302f5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(default='TEMP', editable=False, max_length=6, unique=True, verbose_name='ID Patient'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_id'], name='patients_pa_patient_927c52_idx'),
        ),
    ]
