# Generated by Django 4.2.16 on 2026-03-04 21:46

from django.db import migrations
import secrets
import string

def generate_patient_id():
    """Génère un ID patient alphanumérique unique de 6 caractères"""
    from patients.models import Patient
    while True:
        chars = string.ascii_uppercase + string.digits
        patient_id = ''.join(secrets.choice(chars) for _ in range(6))
        
        # Vérifie que l'ID n'existe pas déjà
        if not Patient.objects.filter(patient_id=patient_id).exists():
            return patient_id

def generate_patient_ids(apps, schema_editor):
    """Génère les patient_id pour les patients existants"""
    Patient = apps.get_model('patients', 'Patient')
    
    for patient in Patient.objects.filter(patient_id='TEMP'):
        patient.patient_id = generate_patient_id()
        patient.save()

def reverse_generate_patient_ids(apps, schema_editor):
    """Reverse migration - remet les patient_id à TEMP"""
    Patient = apps.get_model('patients', 'Patient')
    Patient.objects.all().update(patient_id='TEMP')


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_patient_id_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_patient_ids, reverse_generate_patient_ids),
    ]
