# Generated by Django 5.2.4 on 2026-03-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20260304_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True, verbose_name='ID Patient'),
        ),
    ]
