# Generated by Django 5.2.4 on 2025-08-31 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_dashboard', 'Peut voir le tableau de bord'), ('manage_patients', 'Peut gérer les patients'), ('manage_invoices', 'Peut gérer les factures'), ('manage_reports', 'Peut gérer les comptes rendus'), ('view_reports', 'Peut voir les comptes rendus'), ('manage_appointments', 'Peut gérer les rendez-vous')], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('secretary', 'Secrétaire'), ('accountant', 'Comptable'), ('doctor', 'Médecin')], default='secretary', max_length=20, verbose_name='Rôle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='AccountantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_approve_payments', models.BooleanField(default=True, verbose_name='Peut approuver les paiements')),
                ('can_generate_reports', models.BooleanField(default=True, verbose_name='Peut générer des rapports')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'accountant'}, on_delete=django.db.models.deletion.CASCADE, related_name='accountant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100, verbose_name='Spécialité')),
                ('license_number', models.CharField(max_length=50, verbose_name='Numéro de licence')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SecretaryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_appointments', models.BooleanField(default=True, verbose_name='Peut gérer les rendez-vous')),
                ('can_manage_patients', models.BooleanField(default=True, verbose_name='Peut gérer les patients')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'secretary'}, on_delete=django.db.models.deletion.CASCADE, related_name='secretary_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
