# Generated by Django 5.2.4 on 2025-09-01 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_doctorprofile_user_and_more'),
    ]

    operations = [
    ]
