# Generated by Django 5.2.4 on 2025-09-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_role_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superutilisateur'), ('admin', 'Administrateur'), ('doctor', 'Docteur'), ('secretary', 'Secrétaire'), ('accountant', 'Comptable')], default='secretary', max_length=20, verbose_name='Rôle'),
        ),
    ]
