# Generated by Django 5.2.4 on 2026-03-02 13:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_options_user_department_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date/Heure de connexion')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification de connexion',
                'verbose_name_plural': 'Notifications de connexion',
                'ordering': ['-login_time'],
            },
        ),
    ]
