# Generated by Django 5.2.4 on 2025-08-31 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='reports/', verbose_name='Fichier du compte rendu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('download_count', models.IntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('patient_access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='patients.patientaccess', verbose_name='Accès patient')),
            ],
            options={
                'verbose_name': 'Compte rendu patient',
                'verbose_name_plural': 'Comptes rendus patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
