# Generated by Django 5.2.4 on 2025-09-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientreport',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
    ]
