# Generated by Django 5.2.4 on 2025-08-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name="Nom de l'examen")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Prix (FCFA)')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Durée (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Type d'examen",
                'verbose_name_plural': "Types d'examens",
                'ordering': ['name'],
            },
        ),
    ]
