# Generated by Django 5.2.4 on 2025-09-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examtype',
            index=models.Index(fields=['name'], name='exams_examt_name_1ea611_idx'),
        ),
        migrations.AddIndex(
            model_name='examtype',
            index=models.Index(fields=['price'], name='exams_examt_price_838f38_idx'),
        ),
        migrations.AddIndex(
            model_name='examtype',
            index=models.Index(fields=['is_active'], name='exams_examt_is_acti_89e782_idx'),
        ),
        migrations.AddIndex(
            model_name='examtype',
            index=models.Index(fields=['duration_minutes'], name='exams_examt_duratio_c286f6_idx'),
        ),
        migrations.AddIndex(
            model_name='examtype',
            index=models.Index(fields=['created_at'], name='exams_examt_created_904629_idx'),
        ),
    ]
