# Generated by Django 5.2.4 on 2026-03-05 16:43

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_payments_pa_payment_5c92d7_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coverage_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prise en charge (%)'),
        ),
    ]
