# Generated by Django 5.2.4 on 2026-03-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_coverage_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coverage_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom de la prise en charge'),
        ),
    ]
