# Generated by Django 5.2.4 on 2025-09-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_invoices_in_invoice_e6b546_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('partially_paid', 'Partiellement payée'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='sent', max_length=20, verbose_name='Statut'),
        ),
    ]
