# Generated by Django 5.2.4 on 2025-09-05 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_status'),
        ('patients', '0003_patient_patients_pa_first_n_a142c0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='patient_access',
            field=models.ForeignKey(blank=True, help_text="Clés d'accès générées pour cette facture", null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientaccess', verbose_name='Accès patient'),
        ),
    ]
