# Generated by Django 5.2.4 on 2026-02-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_invoice_patient_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Taux de taxe (%)'),
        ),
    ]
