# Generated by Django 5.2.4 on 2026-03-05 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examtype_exams_examt_name_1ea611_idx_and_more'),
        ('invoices', '0005_alter_invoice_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='exam_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.examtype', verbose_name="Type d'examen"),
        ),
    ]
